### ISSUE TITLE
Update feature dependencies for Jersey JAX-RS Client feature

### ISSUE THREAD

**Issue by modular-mind** [ECF/JaxRSProviders#23]
In my example, I've stripped the target and product down and now have 4 ECF feature dependencies for the Jersey Client feature:

org.eclipse.ecf.core.feature
org.eclipse.ecf.osgi.services.feature
org.eclipse.ecf.discovery.feature
org.eclipse.ecf.remoteservice.feature

The org.eclipse.ecf.osgi.services.feature already lists these two features as dependencies:

org.eclipse.ecf.discovery.feature
org.eclipse.ecf.remoteservice.feature

So if we could have these two features listed as dependencies in the Jersey Client, then the dependency hierarchy would be complete:

org.eclipse.ecf.osgi.services.feature
org.eclipse.ecf.core.feature

My goal is that a developer could add the Jersey Client feature to a product configuration and then click "Add Required" to bring in the minimal feature set needed to run.

I'm not sure how this applies to the Jersey Server or the CXF features, but these dependencies might work for those as well.

**Comment by scottslewis** [comment]
ok.  I'm going to need a couple of days to get this completed because of other commitments.   In the mean time, if you like you can create a pr for the Jersey client feature and I'll prepare and do another release asap.

These projects can/are built by either maven (running install with parent pom), or pde (using target platform in releng/target project.

**Comment by modular-mind** [comment]
There's no rush. Pull request has been created.

**Comment by scottslewis** [comment]
Thanks for creating the pull request.  

I've merged it, updated the version to 1.13.4 and created new release.
