### ISSUE TITLE
Blank default uuid causes issues with multiple bundles providing services

### ISSUE THREAD

**Issue by modular-mind** [ECF/JaxRSProviders#38]
I have two bundles providing remote JAX-RS services with edef_defaults.properties in each. If I specify the endpoint.id like:

endpoint.id:uuid=

Then only the first bundle processed gets its service loaded. If I change the default to:

endpoint.id:uuid=0

Then both bundles' remote services get processed. Perhaps I'm just misunderstanding the default syntax and want to clarify.

Thanks :-)

**Comment by scottslewis** [comment]
The class:  org.eclipse.ecf.osgi.services.remoteserviceadmin.EDEFProperties extends the Properties class (mostly so that it can use the Properties.load method).    As I recall, the Properties.load parser gets confused if there is nothing after the value...i.e. this represents a problem (not parsed as expected):

endpoint.id:uuid=

But this:

endpoint.id:uuid=0

works ok.  The actual value 0 is ignored and so actually it doesn't matter what's after the equals, but there has to be something that's non-whitespace.
