### ISSUE TITLE
Enroute Examples

### ISSUE THREAD

**Issue by yazidaqel** [ECF/JaxRSProviders#8]
Hello, 
Is is possible to change the samples mentionned in the JaxRSProviders folder to use maven same as enroute tutorials.
Thanks in advance

**Comment by scottslewis** [comment]
I'm not exactly sure what you mean.   Do you mean the Karaf features in build/karaf-features.xml?    These currently use http rather than maven...mostly because I need some assistance with getting this project's output to maven central.   If you or others are able to help with that then I've wanted to do so for some time.

As well, this project's bundles can be built with maven...there is pom.xml at top-level that will build examples and distribution provider bundles.   

If you mean something else, please LMK in subsequent comments.

**Comment by yazidaqel** [comment]
Sorry for the misleading question, i just wanted to ask if there is any possibility to add more samples that has the same structure as enRoute tutorials: https://enroute.osgi.org/Tutorial/
My concern is that everyone can have the possibility to use ECF also even if they starts with enRoute tuts.
About the build/karaf-features.xml i will try to help

**Comment by scottslewis** [comment]
I would be happy for someone to contribute the maven config to integrates with the enroute tutorials.

I've done quite a lot of work to get things going easily in bndtools 4...e.g. the ECF bndtools workspace, project templates, and bndrun templates:  https://wiki.eclipse.org/Using_the_Bndtools_Remote_Services_Project_Templates.   I think that's going to be a more effective way to have developers easily integrate ECF RSA and distribution providers into their apps.   

That being said, again I'm completely fine with contributions.

**Comment by yazidaqel** [comment]
Thank you so much, I'm just wondering if there is any guidance that I must follow

**Comment by scottslewis** [comment]
Going to close this issue.  If there are contributions then please reopen.
